### ISSUE TITLE
.pipe not allowed

### ISSUE THREAD

**Issue by lupastance** [jmarca/makedir#2]
Hi,

I'm trying to create a structure folder and I want to concatenate some directories with '.pipe'. Here is the code:

```
gulp.task('tree', function(){
    // DEV folder structure
    makeDir(devDirectory + 'styles/presentation')
        .pipe(makeDir(devDirectory + 'styles/sequence'))
        .pipe(makeDir(devDirectory + 'styles/pws'));
});

```

> TypeError: makeDir(...).pipe is not a function

I don't know if I can use it here or if there is another way to do what I'm trying to do.

Thank you!

**Comment by genzokun** [comment]
Ok I have a solution; using '|' :

`gulp.task('tree', function(){
    // DEV folder structure
    makeDir(devDirectory + 'styles/presentation') |
        makeDir(devDirectory + 'styles/sequence') |
        makeDir(devDirectory + 'styles/pws') |
        makeDir(devDirectory + 'script/presentation') |
        makeDir(devDirectory + 'script/pws');
});`

**Comment by jmarca** [comment]
okay.  I'm not going to implement pipe() at this time.  If I was doing this I would make a list of the desired directories and asynchronously create them, using something like promises, async, or queue.
